const projects=window.AXIS_PROJECTS||{store:{type:'01 / متجر رقمي',title:'AXIS STORE',desc:'مشروع AXIS للتجارة والخدمات الرقمية، يجمع عرض الخدمات وحسابات العملاء ضمن تجربة تحمل هوية الشركة.',features:['واجهة متجر بهوية AXIS البصرية','حسابات وملفات للعملاء','تكامل مع مجتمع AXIS'],url:'https://axissstore.com'},community:{type:'02 / مجتمع رقمي',title:'مجتمع AXIS',desc:'مساحة اجتماعية داخل منظومة AXIS STORE، تتيح للعملاء مشاركة تجاربهم والتواصل مع بعضهم ومتابعة منشورات الإدارة.',features:['منشورات وصور وملفات شخصية','طلبات صداقة ورسائل بين الأعضاء','إعلانات رسمية وإدارة للمجتمع'],url:'https://axissstore.com/community/'}};
const dialog=document.querySelector('#project-dialog');document.querySelectorAll('[data-project]').forEach(button=>button.addEventListener('click',()=>{const project=projects[button.dataset.project];document.querySelector('#modal-type').textContent=project.type;document.querySelector('#modal-title').textContent=project.title;document.querySelector('#modal-desc').textContent=project.desc;document.querySelector('#modal-features').replaceChildren(...project.features.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));const gallery=document.querySelector('#modal-gallery');if(gallery)gallery.replaceChildren(...(project.gallery||[]).map(src=>{const img=document.createElement('img');img.src=src;img.alt=project.title;img.loading='lazy';return img}));const link=document.querySelector('#modal-link');link.hidden=!project.url;if(project.url)link.href=project.url;else link.removeAttribute('href');dialog.showModal()}));document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});
document.querySelector('#copy-brief').addEventListener('click',async()=>{const input=document.querySelector('#brief');const feedback=document.querySelector('#feedback');if(!input.value.trim()){feedback.textContent='اكتب فكرة مشروعك أولًا.';input.focus();return}try{await navigator.clipboard.writeText(input.value.trim());feedback.textContent='تم نسخ الملخص. يمكنك مشاركته مع فريق AXIS.'}catch{input.focus();input.select();feedback.textContent='حدّدنا النص؛ يمكنك نسخه من قائمة جهازك.'}});
const rail=document.querySelector('.project-grid'),cards=[...rail.children],position=document.querySelector('#project-position');let current=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');function updatePosition(){let closest=0,dist=Infinity;cards.forEach((card,i)=>{const d=Math.abs(card.getBoundingClientRect().right-rail.getBoundingClientRect().right);if(d<dist){dist=d;closest=i}});current=closest;position.textContent=`${String(current+1).padStart(2,'0')} / ${String(cards.length).padStart(2,'0')}`;document.querySelector('[data-slide="-1"]').disabled=current===0;document.querySelector('[data-slide="1"]').disabled=current===cards.length-1}document.querySelectorAll('[data-slide]').forEach(button=>button.addEventListener('click',()=>{current=Math.max(0,Math.min(cards.length-1,current+Number(button.dataset.slide)));rail.scrollBy({left:cards[current].getBoundingClientRect().right-rail.getBoundingClientRect().right,behavior:reduced.matches?'instant':'smooth'})}));rail.addEventListener('scroll',updatePosition,{passive:true});updatePosition();if('IntersectionObserver'in window&&!reduced.matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.remove('pending');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.section-head,.services article,.about-copy,.steps article,.contact').forEach(el=>{el.classList.add('reveal','pending');observer.observe(el)})}
// The page is a sequence of horizontal scenes. Each scene scrolls internally if needed.
const main=document.querySelector('main');
const sceneData=[['home','الرئيسية'],['work','المشاريع'],['expertise','الخبرات'],['about','عن AXIS'],['process','منهجنا'],['contact','لنبدأ']];
if(window.AXIS_LABELS)sceneData.forEach((s,i)=>{if(window.AXIS_LABELS[i])s[1]=window.AXIS_LABELS[i]});
document.querySelector('.process').id='process';
const discipline=document.querySelector('.disciplines'),footer=document.querySelector('footer');
const scenes=sceneData.map(([id,label])=>{const section=document.getElementById(id),scene=document.createElement('div');scene.className='scene';scene.setAttribute('role','region');scene.setAttribute('aria-label',label);scene.tabIndex=-1;scene.append(section);if(id==='home')scene.append(discipline);if(id==='contact')scene.append(footer);main.append(scene);return scene});
document.body.classList.add('spatial-site');document.querySelectorAll('.reveal').forEach(el=>el.classList.remove('pending'));
const sceneNav=document.createElement('nav');sceneNav.className='scene-nav';sceneNav.setAttribute('aria-label','التنقل بين أقسام البورتفوليو');
const progress=document.createElement('div');progress.className='scene-progress';progress.setAttribute('aria-hidden','true');
const tabs=document.createElement('div');tabs.className='scene-tabs';
const status=document.createElement('span');status.className='scene-status';status.setAttribute('aria-live','polite');
const next=document.createElement('button');next.className='scene-next';next.type='button';next.textContent='التالي';
let sceneIndex=0,lastMove=0;const sceneButtons=sceneData.map(([id,label],i)=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span>${label}`;b.addEventListener('click',()=>goScene(i));tabs.append(b);return b});sceneNav.append(progress,tabs,status,next);main.after(sceneNav);
function goScene(index,focus=false,writeHistory=true){
 if(index<0||index>=scenes.length)return;
 const previous=sceneIndex;sceneIndex=index;lastMove=Date.now();
 scenes.forEach((scene,i)=>{scene.getAnimations().forEach(a=>a.cancel());scene.hidden=i!==index;scene.inert=i!==index;scene.setAttribute('aria-hidden',String(i!==index));scene.style.zIndex=i===index?'2':'1'});
 main.style.transform='none';
 sceneButtons.forEach((b,i)=>{if(i===index)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
 document.querySelectorAll('header a[href^="#"]').forEach(a=>{if(a.hash==='#'+sceneData[index][0])a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});
 status.textContent=`${String(index+1).padStart(2,'0')} / 06`;progress.style.width=`${(index+1)/scenes.length*100}%`;next.disabled=index===scenes.length-1;
 const active=sceneButtons[index];tabs.scrollTo({left:tabs.scrollLeft+active.getBoundingClientRect().left-tabs.getBoundingClientRect().left+(active.offsetWidth-tabs.clientWidth)/2,behavior:reduced.matches?'instant':'smooth'});
 if(previous!==index&&!reduced.matches){
  const direction=index>previous?1:-1,outgoing=scenes[previous],incoming=scenes[index];outgoing.hidden=false;
  const out=outgoing.animate([{opacity:1,transform:'translateX(0) scale(1)'},{opacity:0,transform:`translateX(${direction*6}%) scale(.985)`}],{duration:300,easing:'ease-in',fill:'forwards'});
  out.onfinish=()=>{if(sceneIndex!==previous)outgoing.hidden=true;out.cancel()};
  incoming.animate([{opacity:0,transform:`perspective(1200px) translateX(${-direction*7}%) rotateY(${-direction*3}deg) scale(.985)`},{opacity:1,transform:'perspective(1200px) translateX(0) rotateY(0) scale(1)'}],{duration:550,delay:140,fill:'backwards',easing:'cubic-bezier(.22,.75,.18,1)'});
 }
 if(writeHistory&&location.hash!=='#'+sceneData[index][0])history.pushState(null,'','#'+sceneData[index][0]);if(focus)scenes[index].focus({preventScroll:true});if(index===1)requestAnimationFrame(updatePosition);
}
next.addEventListener('click',()=>goScene(sceneIndex+1,true));
document.addEventListener('click',event=>{const a=event.target.closest('a[href^="#"]');if(!a)return;const index=sceneData.findIndex(([id])=>'#'+id===a.hash);if(index>=0){event.preventDefault();goScene(index,true)}});
window.addEventListener('popstate',()=>goScene(Math.max(0,sceneData.findIndex(([id])=>'#'+id===location.hash)),false,false));
document.addEventListener('keydown',event=>{if(dialog.open||event.target.closest('input,textarea,select,button,a,[contenteditable]'))return;if(event.key==='ArrowLeft'){event.preventDefault();goScene(sceneIndex+1,true)}if(event.key==='ArrowRight'){event.preventDefault();goScene(sceneIndex-1,true)}});
let touchStart=null;main.addEventListener('touchstart',event=>{if(event.target.closest('.project-grid,textarea,input,button,a')){touchStart=null;return}const t=event.touches[0];touchStart={x:t.clientX,y:t.clientY}},{passive:true});main.addEventListener('touchend',event=>{if(!touchStart||dialog.open)return;const t=event.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)goScene(sceneIndex+(dx>0?1:-1));touchStart=null},{passive:true});
main.addEventListener('wheel',event=>{if(dialog.open||event.target.closest('.project-grid,textarea,input'))return;const scene=scenes[sceneIndex];let direction=0;if(Math.abs(event.deltaX)>Math.abs(event.deltaY)&&Math.abs(event.deltaX)>12)direction=event.deltaX<0?1:-1;else if(Math.abs(event.deltaY)>12){const bottom=scene.scrollTop+scene.clientHeight>=scene.scrollHeight-3;const top=scene.scrollTop<=0;if(event.deltaY>0&&bottom)direction=1;if(event.deltaY<0&&top)direction=-1}if(direction){event.preventDefault();if(Date.now()-lastMove>950)goScene(sceneIndex+direction)}},{passive:false});
goScene(Math.max(0,sceneData.findIndex(([id])=>'#'+id===location.hash)),false,false);
